GLADE_FILE = "../project.glade"
ABOUT_FILE = "../about.glade"
FILE_CHOOSER_FILE = "../file_chooser.glade"
OUTPUT_CHOOSER_FILE = "../output_chooser.glade"
RESULT_FILE = "../result.glade"
LEARN_DIALOG_FILE = "../learn_dialog.glade"
SETTINGS_FILE = "../settings.glade"
